name: CI Workflow for React and Express

on:
  push:
    branches:
      - master  # Triggers on pushes to master
  pull_request:
    branches:
      - master  # Triggers on pull requests to master

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Execution decider
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
              src:
                - 'frontend/**'
                - '.github/**'
                - '.vscode/**'
                - 'README.md'

      - name: Set up Node.js
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "20"  # Use Node.js v20

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        working-directory: ./frontend
        run: npm install

      - name: Build React app
        if: steps.changes.outputs.src == 'true'
        working-directory: ./frontend
        run: npm run build

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Execution decider
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
              src:
                - 'backend/**'
                - '.github/**'
                - '.vscode/**'
                - 'README.md'

      - name: Set up Node.js
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "20"  # Use Node.js v20

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        working-directory: ./backend
        run: npm install

      - name: Build backend
        if: steps.changes.outputs.src == 'true'
        working-directory: ./backend
        run: npm run build
